

// Console Link: shopping cart solution......


// 1. Filesystem> add folder to workspace + allow....

// 2. save codes in snippets and run it manually in any other console even......

// 3. Few shortcuts....
//    ctrl + shift + o       to see all the functions available.
//    ctrl + g               to move cursor to the given line....


